### ISSUE TITLE
Change addt command error

### ISSUE THREAD

**Issue by beginner-web-developer** [AY2425S1-CS2103T-F13-4/tp#109]
Should include a warning to the user that the command is only supported in the person page (like what is don't for findt)

**Comment by kngys** [comment]
![image](https://github.com/user-attachments/assets/58955e70-0c0d-4d61-8dde-12e456972883)
Can I check where did the `findt` command specify that it is only supported in the person page? Because when tried `listt` followed by `findt 1 sell` in the list transaction view, the `findt` command still worked. Are we supposed to make all the transaction-related commands only work in the person page?

**Comment by reginateh** [comment]
I suppose I wrote it in the error message (which shows the command format) and user guide. But yea for now it is not caught as an error. `findt` is only available in person page because one of its parameters is the person index. If a command requires person index, it should only be available in person page. Same for transaction.

**Comment by reginateh** [comment]
Issue #116 opened to address `findt`'s issue. You can refer to it if you need :)
