### ISSUE TITLE
Improve handling of inputs for `add` command 

### ISSUE THREAD

**Issue by kngys** [AY2425S1-CS2103T-F13-4/tp#114]
When I try to add a phone number containing a String, it is not allowed.
![image](https://github.com/user-attachments/assets/b36a6fd5-83f5-4e01-b7c6-5c43420b07ff)

Not sure if this is considered as overzealous input validation. Maybe can consider displaying a warning instead of blocking?
![image](https://github.com/user-attachments/assets/73c9837b-0781-4af4-bc6c-b297fce0362b)

**Comment by trpmy** [comment]
Now that I'm thinking about it, is a warning necessary? The point of a warning is to warn against potentially unintended behaviours, but let's say I'm a user who notes down phone number in a certain format like 9999 9999 (HP) or 88888888 (Work) because I want to include that info, then the warning every time seems a little annoying

My reasoning is just that, if our concern is to make the p/ field more customisable, we can simply allow the users to interpret how they want to use that field as needed in this case? I'd love to hear suggestions if you have any better alternative than just letting phone be free text field (which also feels somewhat odd to me)

**Comment by kngys** [comment]
In my opinion there's probably no clear answer as to which is best, I think what matters is probably being able to justify why the feature was implemented in this manner is someone questions it since the definition of a feature flaw seems quite subjective. Up to you whether you want to keep it as it is or change it!
